### ISSUE TITLE
Code completion suggestion error

### ISSUE THREAD

**Issue by zhishengzhang** [openpilot-hub/devpilot-intellij#48]
devpilot version：2.4.2
ide：PyCharm 2023.3.2 (Community Edition)
`pycharmcom.intellij.openapi.diagnostic.RuntimeExceptionWithAttachments: Read access is allowed from inside read-action (see Application.runReadAction()); see https://jb.gg/ij-platform-threading for details
Current thread: Thread[ApplicationImpl pooled thread 7,4,main] 335388483 (EventQueue.isDispatchThread()=false)
SystemEventQueueThread: Thread[AWT-EventQueue-0,6,main] 1319861973
        at com.intellij.util.concurrency.ThreadingAssertions.createThreadAccessException(ThreadingAssertions.java:149)
        at com.intellij.util.concurrency.ThreadingAssertions.softAssertReadAccess(ThreadingAssertions.java:107)
        at com.intellij.openapi.application.impl.ApplicationImpl.assertReadAccessAllowed(ApplicationImpl.java:1012)
        at com.intellij.workspaceModel.core.fileIndex.impl.WorkspaceFileIndexDataImpl.ensureIsUpToDate(WorkspaceFileIndexDataImpl.kt:134)
        at com.intellij.workspaceModel.core.fileIndex.impl.WorkspaceFileIndexDataImpl.getFileInfo(WorkspaceFileIndexDataImpl.kt:75)
        at com.intellij.workspaceModel.core.fileIndex.impl.WorkspaceFileIndexImpl.getFileInfo(WorkspaceFileIndexImpl.kt:247)
        at com.intellij.workspaceModel.core.fileIndex.impl.WorkspaceFileIndexImpl.findFileSetWithCustomData(WorkspaceFileIndexImpl.kt:230)
        at com.intellij.openapi.roots.impl.ProjectFileIndexImpl.getModuleForFile(ProjectFileIndexImpl.java:97)
        at com.zhongan.devpilot.util.VirtualFileUtil.getRelativeFilePath(VirtualFileUtil.java:59)
        at com.zhongan.devpilot.integrations.llms.aigateway.AIGatewayServiceProvider.instructCompletion(AIGatewayServiceProvider.java:243)
        at com.zhongan.devpilot.completions.prediction.CompletionFacade.retrieveCompletions(CompletionFacade.java:114)
        at com.zhongan.devpilot.completions.prediction.CompletionFacade.retrieveCompletions(CompletionFacade.java:57)
        at com.zhongan.devpilot.completions.inline.InlineCompletionHandler.retrieveInlineCompletion(InlineCompletionHandler.java:186)
        at com.zhongan.devpilot.completions.inline.InlineCompletionHandler.lambda$refetchCompletionsAfterDebounce$6(InlineCompletionHandler.java:137)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:272)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
        at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
        at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
        at java.base/java.lang.Thread.run(Thread.java:840)`

**Comment by zhishengzhang** [comment]
![image](https://github.com/user-attachments/assets/6f79df0f-9d01-41a7-b89a-8407d19e8fa3)

**Comment by xiangtianyu** [comment]
Thanks for feedback, wo will fix it soon
